### ISSUE TITLE
Update dataset download URL (landcoverAI)

### ISSUE THREAD

**Issue by gjustin40** [Seyed-Ali-Ahmadi/Awesome_Satellite_Benchmark_Datasets#4]
Thanks for providing good information about Satellite Benchmark dataset.

I want to tell you about new URL of **LandcoverAI** dataset
https://landcover.ai/  --->   https://landcover.ai.linuxpolska.com/
(I found it from https://arxiv.org/abs/2005.02264)

I hope this helps

**Comment by Seyed-Ali-Ahmadi** [comment]
Oh, great. Thanks. I replace it with the new one.
